#!/bin/sh
searchEngine="https://duckduckgo.com/"
if [ $# -ne 0 ]
then
	searchParameter="?q="
	requestStr=$1
	shift
	for i in $@
	do
		requestStr=$requestStr"%20"$i
	done
fi
surf $searchEngine$searchParameter$requestStr
